# Generated by Django 2.0.4 on 2018-05-04 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0002_auto_20180504_2105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='priceSup',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='stock',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
    ]
