# Generated by Django 2.0.4 on 2018-05-04 22:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0004_auto_20180504_2313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='dateFin',
            field=models.DateTimeField(default=datetime.date(2018, 5, 4)),
        ),
    ]
