# Generated by Django 2.0.4 on 2018-05-04 22:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0006_auto_20180504_2339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='dateFin',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
