# Generated by Django 2.0.4 on 2018-05-04 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0007_auto_20180504_2342'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='daily',
            field=models.BooleanField(default=False),
        ),
    ]
