# Generated by Django 2.0.4 on 2018-05-05 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0010_stock_first_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='first_quantity',
            field=models.IntegerField(default=0, editable=False),
        ),
    ]
