# Generated by Django 2.0.4 on 2018-05-05 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0011_auto_20180505_0132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='first_quantity',
            field=models.IntegerField(default=0),
        ),
    ]
