# Generated by Django 2.0.4 on 2018-05-05 15:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0012_auto_20180505_0149'),
    ]

    operations = [
        migrations.CreateModel(
            name='BillingAddress',
            fields=[
                ('address_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ecommerce.Address')),
            ],
            bases=('ecommerce.address',),
        ),
        migrations.CreateModel(
            name='ShippingAddress',
            fields=[
                ('address_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ecommerce.Address')),
            ],
            bases=('ecommerce.address',),
        ),
        migrations.RenameField(
            model_name='address',
            old_name='value',
            new_name='address',
        ),
        migrations.AddField(
            model_name='address',
            name='city',
            field=models.CharField(default='', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='address',
            name='company',
            field=models.CharField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='address',
            name='country',
            field=models.CharField(default='', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='address',
            name='post_code',
            field=models.CharField(default='', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='address',
            name='region',
            field=models.CharField(default='', max_length=254),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='address',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='ecommerce.Profil'),
        ),
    ]
