# Generated by Django 2.0.4 on 2018-05-06 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0015_auto_20180506_0033'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='number_views',
            field=models.IntegerField(default=0),
        ),
    ]
