# Generated by Django 2.0.4 on 2018-05-06 01:11

from django.db import migrations, models
import ecommerce.models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0016_product_number_views'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='image',
            field=models.ImageField(default='/images/NoImageBran.png', upload_to=ecommerce.models.PathAndRename('images/2018/05/06')),
        ),
    ]
