# Generated by Django 2.0.4 on 2018-05-06 22:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0019_brand_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profil',
            name='dateBorn',
        ),
        migrations.RemoveField(
            model_name='profil',
            name='facebook',
        ),
        migrations.RemoveField(
            model_name='profil',
            name='function',
        ),
        migrations.RemoveField(
            model_name='profil',
            name='pays',
        ),
        migrations.RemoveField(
            model_name='profil',
            name='service',
        ),
        migrations.RemoveField(
            model_name='profil',
            name='ville',
        ),
        migrations.RemoveField(
            model_name='profil',
            name='website',
        ),
        migrations.RemoveField(
            model_name='profil',
            name='youtube',
        ),
    ]
