# Generated by Django 2.0.4 on 2018-05-07 03:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0021_auto_20180507_0413'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sale',
            old_name='dateFin',
            new_name='date_end',
        ),
    ]
