# Generated by Django 2.0.4 on 2018-05-07 03:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0022_auto_20180507_0416'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commerceratting',
            old_name='nom',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='sale',
            old_name='daily',
            new_name='is_daily',
        ),
    ]
