# Generated by Django 2.0.4 on 2018-05-07 03:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0023_auto_20180507_0444'),
    ]

    operations = [
        migrations.RenameField(
            model_name='slide',
            old_name='dateAdd',
            new_name='date_add',
        ),
    ]
