# Generated by Django 2.0.4 on 2018-05-07 03:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0024_auto_20180507_0449'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='dateAdd',
            new_name='date_add',
        ),
    ]
