# Generated by Django 2.0.4 on 2018-05-11 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0026_auto_20180511_0405'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailing',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
