# Generated by Django 2.0.4 on 2018-05-11 03:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0028_auto_20180511_0449'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='billingaddress',
            name='address_ptr',
        ),
        migrations.RemoveField(
            model_name='billingaddress',
            name='user',
        ),
        migrations.RemoveField(
            model_name='shippingaddress',
            name='address_ptr',
        ),
        migrations.RemoveField(
            model_name='shippingaddress',
            name='user',
        ),
        migrations.DeleteModel(
            name='BillingAddress',
        ),
        migrations.DeleteModel(
            name='ShippingAddress',
        ),
    ]
