# Generated by Django 2.0.4 on 2018-05-11 03:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0029_auto_20180511_0450'),
    ]

    operations = [
        migrations.CreateModel(
            name='BillingAddress',
            fields=[
                ('address_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ecommerce.Address')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='ecommerce.Profil')),
            ],
            bases=('ecommerce.address',),
        ),
        migrations.CreateModel(
            name='ShippingAddress',
            fields=[
                ('address_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ecommerce.Address')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='ecommerce.Profil')),
            ],
            bases=('ecommerce.address',),
        ),
    ]
