# Generated by Django 2.0.4 on 2018-05-11 16:46

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0030_billingaddress_shippingaddress'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField()),
                ('date_add', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='mailing',
            name='date_add',
            field=models.DateField(auto_now_add=True, default=datetime.datetime(2018, 5, 11, 16, 46, 16, 386436, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
