# Generated by Django 2.0.4 on 2018-05-12 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0032_auto_20180512_0321'),
    ]

    operations = [
        migrations.AddField(
            model_name='slide',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
