# Generated by Django 2.0.4 on 2018-05-12 19:54

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0033_slide_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commerceratting',
            name='email',
        ),
        migrations.AddField(
            model_name='commerceratting',
            name='date_add',
            field=models.DateField(auto_now_add=True, default=datetime.datetime(2018, 5, 12, 19, 54, 22, 403336, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
