# Generated by Django 2.0.4 on 2018-05-17 23:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0039_auto_20180517_0017'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommerceSCategoryOne',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecommerce.CommerceCategory')),
            ],
        ),
        migrations.CreateModel(
            name='CommerceSCategoryTwo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecommerce.CommerceSCategoryOne')),
            ],
        ),
        migrations.AlterField(
            model_name='commercescategory',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecommerce.CommerceSCategoryTwo'),
        ),
    ]
