# Generated by Django 2.0.4 on 2018-05-17 23:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0040_auto_20180517_2300'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commercescategory',
            old_name='category',
            new_name='category_two',
        ),
        migrations.RenameField(
            model_name='commercescategorytwo',
            old_name='category',
            new_name='category_one',
        ),
    ]
