# Generated by Django 2.0.4 on 2018-05-19 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0044_auto_20180519_2303'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='Delivery_time',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='packaging_detail',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
