# Generated by Django 2.0.4 on 2018-05-19 23:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0045_auto_20180519_2313'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='Delivery_time',
            new_name='delivery_time',
        ),
    ]
