# Generated by Django 2.0.4 on 2018-05-31 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0059_auto_20180531_2303'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='tel',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
