# Generated by Django 2.0.4 on 2018-05-16 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_auto_20180506_2306'),
    ]

    operations = [
        migrations.AddField(
            model_name='profil',
            name='tel',
            field=models.CharField(blank=True, default='', max_length=300, null=True),
        ),
    ]
