# Generated by Django 2.0.4 on 2018-05-18 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_profil_tel'),
    ]

    operations = [
        migrations.AddField(
            model_name='profil',
            name='type_customer',
            field=models.CharField(choices=[('Ordinary', 'Ordinary'), ('Professional', 'Professional'), ('Supplier', 'Supplier')], default='Ordinary', max_length=20),
        ),
    ]
