# Generated by Django 2.0.4 on 2018-05-28 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_auto_20180523_0143'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profil',
            name='type_customer',
        ),
        migrations.AddField(
            model_name='profil',
            name='is_professional',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profil',
            name='is_supplier',
            field=models.BooleanField(default=False),
        ),
    ]
